-- Device warning table.
-- First version stores warning trigger results and reserved closure fields.
CREATE TABLE IF NOT EXISTS fe_device_warning (
    warning_id bigint NOT NULL AUTO_INCREMENT COMMENT 'Warning ID',
    warning_type varchar(64) NOT NULL COMMENT 'Warning type: low_pressure/high_pressure/low_battery/insufficient_extinguisher/extinguisher_expired/abnormal_temperature/gateway_offline/suspected_fire',
    object_type varchar(32) NOT NULL COMMENT 'Primary object type: sensor/extinguisher/fire_point/gateway',
    object_id bigint NOT NULL COMMENT 'Primary local object ID',
    dept_id bigint DEFAULT NULL COMMENT 'Local governed dept ID',
    source_dept_id bigint DEFAULT NULL COMMENT 'SDK credential source dept ID',
    fire_point_id bigint DEFAULT NULL COMMENT 'Related fire point ID',
    gateway_id bigint DEFAULT NULL COMMENT 'Related gateway ID',
    sensor_id bigint DEFAULT NULL COMMENT 'Related sensor ID',
    extinguisher_id bigint DEFAULT NULL COMMENT 'Related extinguisher ID',
    trigger_time datetime DEFAULT NULL COMMENT 'First trigger time',
    last_trigger_time datetime DEFAULT NULL COMMENT 'Latest trigger time',
    window_start_time datetime DEFAULT NULL COMMENT 'Evidence window start time',
    window_end_time datetime DEFAULT NULL COMMENT 'Evidence window end time',
    sample_count int DEFAULT NULL COMMENT 'Consecutive sample or snapshot count',
    threshold_snapshot varchar(500) DEFAULT NULL COMMENT 'Threshold snapshot',
    evidence_summary varchar(1000) DEFAULT NULL COMMENT 'Evidence summary',
    warning_status varchar(32) NOT NULL DEFAULT 'pending' COMMENT 'Warning status: pending/processing/resolved/false_alarm',
    confirm_by varchar(64) DEFAULT NULL COMMENT 'Confirmed by',
    confirm_time datetime DEFAULT NULL COMMENT 'Confirmed time',
    handle_by varchar(64) DEFAULT NULL COMMENT 'Handled by',
    handle_time datetime DEFAULT NULL COMMENT 'Handled time',
    resolve_by varchar(64) DEFAULT NULL COMMENT 'Resolved by',
    resolve_time datetime DEFAULT NULL COMMENT 'Resolved time',
    false_alarm_reason varchar(500) DEFAULT NULL COMMENT 'False alarm reason',
    remark varchar(500) DEFAULT NULL COMMENT 'Remark',
    create_by varchar(64) DEFAULT '' COMMENT 'Created by',
    create_time datetime DEFAULT NULL COMMENT 'Created time',
    update_by varchar(64) DEFAULT '' COMMENT 'Updated by',
    update_time datetime DEFAULT NULL COMMENT 'Updated time',
    del_flag char(1) NOT NULL DEFAULT '0' COMMENT 'Delete flag: 0 exists, 2 deleted',
    PRIMARY KEY (warning_id),
    KEY idx_warning_object_status (warning_type, object_type, object_id, warning_status),
    KEY idx_warning_dept_time (dept_id, last_trigger_time),
    KEY idx_warning_fire_point (fire_point_id, warning_status),
    KEY idx_warning_sensor (sensor_id, warning_status),
    KEY idx_warning_extinguisher (extinguisher_id, warning_status),
    KEY idx_warning_gateway (gateway_id, warning_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Device warning table';
